

name: CI

on:
 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
   
    runs-on: ubuntu-latest

  
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      name:Checkout
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses:docker/login-action@v1
        with:
         username:${{secrets.DOCKER_HUB_MADHURI}}
         password:${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v2
           with:
           context: .
           file: ./Dockerfile
           push: true
           tags: ${{secrets.DOCKER_HUB_MADHURI}}/simplewhale:latest

     
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
